Some small fixes to the CI job

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -232,6 +232,9 @@ jobs:
           maint/RunPerlTest
 
   chaffinch:
+    # Job to verify that the CMake "unity" build (single-file / jumbo build) passes.
+    # If this fails, it's usually because two different files define some file-static
+    # functions or macros which collide.
     name: CMake unity build
     runs-on: ubuntu-latest
     steps:
@@ -250,17 +253,31 @@ jobs:
         run: cd build && ctest -j3 --output-on-failure
 
   heron:
+    # Job to verify that the tasks performed by PrepareRelease have been done. It is
+    # the committer's responsibility (currently) to run PrepareRelease themselves when
+    # making a PR, so that everything is kept in-sync.
     name: Check for PrepareRelease cleanliness
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04 # TODO: Update to ubuntu-latest when that switches to 24.04
     steps:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
           submodules: false
+          fetch-depth: 0
+          fetch-tags: false
 
       - name: PrepareRelease
         run: maint/PrepareRelease
 
       - name: Working directory clean
         run:  |
-          [ -z "`git status --porcelain`" ]
+          if [ -n "`git status --porcelain`" ] ; then
+            (
+              echo "Dirty working tree! Affected files after PrepareRelease:"
+              git status --porcelain || true
+              echo ""
+              echo "Diff after PrepareRelease:"
+              git diff || true
+            ) >&2
+            exit 1
+          fi
